name: CI

on: 
  push:
    branches: 
      - master

jobs:
  restore:
    runs-on: [ubuntu-latest]
    name: Dotnet Restore
    steps:
      - run: dotnet restore
  
  build:
    runs-on: [ubuntu-latest]
    name: Dotnet Build
    steps:
      - run: dotnet build --configuration Release
  test:
    runs-on: [ubuntu-latest]
    name: Tests
    steps:
      - run: dotnet test
  nuget:
    runs-on: [ubuntu-latest]
    name: Setup Nuget.exe
    steps:
      - uses: warrenbuckley/Setup-Nuget@v1
  pack: 
    runs-on: [ubuntu-latest]
    name: "Pack to a Nuget Package"
    steps:
      - run: nuget pack cryptography.nuspec

  publish: 
    runs-on: [ubuntu-latest]
    name: "Publish to nuget"
    steps:
      - run: dotnet push Kifreak.Cryptography.*.nupkg -k oy2jcwfxfpozklm435uaxhzslf3m3gduzlsktoxvkthaxi -s https://api.nuget.org/v3/index.json
